### ISSUE TITLE
TextInput outline is having a weird stroke on the web

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#1710]
## Environment

![image](https://user-images.githubusercontent.com/1866564/75818547-a66b1000-5dcb-11ea-98d8-ae66f01d827e.png)

## Description

Target: web

## Reproducible Demo

https://github.com/callstack/react-native-paper-login-template (see https://github.com/callstack/react-native-paper-login-template/issues/4)

**Comment by kopax** [comment]
Does anybody have a workaround for this?

**Comment by kopax** [comment]
This can be fix using: 

```css
:focus {
    outline-color: transparent;
    outline-style: none;
}
```

https://stackoverflow.com/questions/935559/remove-safari-chrome-textinput-textarea-glow
